version: '3'

services:
  app1:
    container_name : cpasajes
    image: ipasajes
    build:
      context: ./RUTAS.REST.PASAJE
      dockerfile: Dockerfile
  app2:
    container_name : cpasajes
    image: ipasajes
    build:
      context: ./RUTAS.REST.PASAJE
      dockerfile: Dockerfile
  app3:
    container_name : cpasajes
    image: ipasajes
    build:
      context: ./RUTAS.REST.PASAJE
      dockerfile: Dockerfile

  nginx:
    image: nginx
    links:
     - app1:app1
     - app2:app2
     - app3:app3
    ports:
     - "5100:5100"

  mongodb:
    container_name: mongodb
    image: mongo